/**
 * Domain models shared across features. These are hand-written and intentionally
 * decoupled from the raw database row shapes (see `database.ts`). Service
 * functions map DB rows <-> these models so UI and business logic never depend
 * on Supabase column naming.
 */

export type EventCategory =
  | 'class'
  | 'meeting'
  | 'personal'
  | 'health'
  | 'social'
  | 'other';

/**
 * Where a record came from. `manual` is user-created in WassupDay;
 * `device_calendar` is read (never written) from the OS Calendar app.
 * `import` / `ai` are reserved for future sync sources.
 */
export type RecordSource = 'manual' | 'import' | 'ai' | 'device_calendar';

export type TaskPriority = 'low' | 'medium' | 'high';
export type TaskStatus = 'todo' | 'completed';

export interface Profile {
  id: string;
  displayName: string | null;
  timezone: string;
  createdAt: string;
  updatedAt: string;
}

export interface CalendarEvent {
  id: string;
  userId: string;
  title: string;
  description: string | null;
  /** ISO 8601, timezone-aware (stored as timestamptz). */
  startTime: string;
  /** ISO 8601, timezone-aware. Always >= startTime. */
  endTime: string;
  location: string | null;
  category: EventCategory;
  source: RecordSource;
  /** True for calendar all-day events. Undefined/false for normal timed events. */
  isAllDay?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Task {
  id: string;
  userId: string;
  title: string;
  description: string | null;
  /** ISO 8601 date-time or null when the task has no due date. */
  dueDate: string | null;
  priority: TaskPriority;
  /** Estimated duration in minutes, or null. */
  estimatedDuration: number | null;
  status: TaskStatus;
  source: RecordSource;
  createdAt: string;
  updatedAt: string;
}

/** A detected overlap between two events on the same day. Deterministic, no AI. */
export interface ScheduleConflict {
  a: CalendarEvent;
  b: CalendarEvent;
  /** Overlap window, ISO 8601. */
  overlapStart: string;
  overlapEnd: string;
}

/**
 * The lightweight, read-only snapshot the Today screen and the widgets both
 * render. Generated by a single reusable function (Phase 6 / Phase 8) so the
 * widget never runs its own expensive queries.
 */
export interface TodaySnapshot {
  /** The local calendar date this snapshot describes, YYYY-MM-DD. */
  date: string;
  currentEvent: CalendarEvent | null;
  nextEvent: CalendarEvent | null;
  upcomingEvents: CalendarEvent[];
  priorityTasks: Task[];
  overdueTasks: Task[];
  conflicts: ScheduleConflict[];
  /** ISO 8601 timestamp the snapshot was generated. */
  updatedAt: string;
}
